//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMaths.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Questions = new HashSet<Question>();
            this.Records = new HashSet<Record>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public float Rank { get; set; }
        public int LevelId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Record> Records { get; set; }
    }
}
