//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMaths.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoverLevel
    {
        public CoverLevel()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int Id { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<Record> Records { get; set; }
    }
}
