//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMaths.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string SessionKey { get; set; }
        public int LevelId { get; set; }
        public int UserRoleId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual ICollection<Record> Records { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
